version: "1"
services:
  influxdb:
    image: "influxdb:latest"
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./influxdb:/var/lib/influxdb
  web-perf-lighthouse:
    image: "web-perf-lighthouse"
    ports:
      - 3000:3000
    environment:
      - HOST=influxdb
    volumes:
      - ./config.json:/usr/src/web-perf-lighthouse/config.json
      - ./plugins/web-perf-lighthouse/reports:/usr/src/web-perf-lighthouse/reports
      - ./plugins/web-perf-lighthouse/logs:/usr/src/web-perf-lighthouse/logs
    depends_on:
      - influxdb
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=secret
    volumes:
      - "./grafana_data:/var/lib/grafana"
      - "./config/grafana/provisioning:/etc/grafana/provisioning"
      - "./config/grafana/grafana.ini:/etc/grafana/grafana.ini"
    depends_on:
      - influxdb
    user: ${CURRENT_UID}
  chronograf:
    image: "chronograf:latest"
    ports:
      - 8888:8888
    depends_on:
      - influxdb
