version: "3"
services:
  # DATABASE
  influxdb:
    image: "influxdb:latest"
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./packages/influxdb/volume:/var/lib/influxdb
  chronograf:
    image: "chronograf:latest"
    ports:
      - 8888:8888
    depends_on:
      - influxdb

  # DASHBOARD
  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - "./packages/grafana/volume:/var/lib/grafana"
      - "./packages/grafana/provisioning:/etc/grafana/provisioning"
      - "./packages/grafana/grafana.ini:/etc/grafana/grafana.ini"
    depends_on:
      - influxdb
    user: ${CURRENT_UID}

  # lighthouse
  # web-perf-lighthouse:
  #   image: "web-perf-lighthouse"
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - HOST=influxdb
  #   volumes:
  #     - ./config.json:/usr/src/web-perf-lighthouse/config.json
  #     - ./plugins/web-perf-lighthouse/reports:/usr/src/web-perf-lighthouse/reports
  #     - ./plugins/web-perf-lighthouse/logs:/usr/src/web-perf-lighthouse/logs
  #   depends_on:
  #     - influxdb

